### PR TITLE
[DSI-7169] Updated invitation api to create users when `entraOid` is provided in the request body

### PR DESCRIPTION
**Pull request by ipredoi**
## Summary
**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7169
## Changes
-  updated code to handle the new columns (`is_entra`,`entra_oid` and `entra_linked`) aded into `dbo.user` table   
-  Fixed linting issues and removed unused commented-out code in `src/app/invitations/api/createUser.js`    
-  Removed old unused code related to `userFileAdapter` and updated the `readme.md` file to reflect these changes.
-  Fixed 4 high vulnerabilities using `npm audit fix` command
-  Fixed all 8 moderate vulnerabilities 
- Refactor: moved `findByUsername` functionality into a helper to improve unit testing coverage
- Updated unit tests for `createUser` and `userSequelizeAdapter.create` after refactor to fully cover the functionality

### CODE REVIEW

**Review by trickyward — DISMISSED** [review]
Looks good to me.

**Review by kruncher — APPROVED** [review]
Looks good to me 👍

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Review by shravani-kondaparti — APPROVED** [review]
Regression tests passed in Test env

**Pull request merged**
